# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

sp_show_storage <- function(x) {
    .Call('_m3addon_sp_show_storage', PACKAGE = 'm3addon', x)
}

subsetSM <- function(a, rind, cind) {
    .Call('_m3addon_subsetSM', PACKAGE = 'm3addon', a, rind, cind)
}

calculateScoresCPP <- function(a, Rgenevec) {
    .Call('_m3addon_calculateScoresCPP', PACKAGE = 'm3addon', a, Rgenevec)
}

logNormCPP <- function(a) {
    .Call('_m3addon_logNormCPP', PACKAGE = 'm3addon', a)
}

colStdDev <- function(a) {
    .Call('_m3addon_colStdDev', PACKAGE = 'm3addon', a)
}

rowStdDev <- function(a) {
    .Call('_m3addon_rowStdDev', PACKAGE = 'm3addon', a)
}

vstExprsCPP <- function(a, eP, aD, return_sparse = TRUE, calc_zeros = FALSE) {
    .Call('_m3addon_vstExprsCPP', PACKAGE = 'm3addon', a, eP, aD, return_sparse, calc_zeros)
}

iterateSparseMatrixCPP <- function(a) {
    invisible(.Call('_m3addon_iterateSparseMatrixCPP', PACKAGE = 'm3addon', a))
}

